import "./globals.css";
import { Header } from "@/components/Header";
import { Providers } from "@/components/Providers";
import type { Metadata } from "next";
import { Lora } from "next/font/google";

const loraFont = Lora({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-lora"
});

export const metadata: Metadata = {
  title: "Igniz",
  description: "Generated by create next app"
};

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang='ru' className={loraFont.className}>
      <body style={{ height: "100%" }}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
